{
  "comments": [
    {
      "key": {
        "uuid": "18839a89_129981ee",
        "filename": "lib/nvmf/nvmf.c",
        "patchSetId": 9
      },
      "lineNbr": 720,
      "author": {
        "id": 1012251
      },
      "writtenOn": "2018-12-11T08:10:07Z",
      "side": 1,
      "message": "When this call fails, some retry mechanism is necessary here? Next call may success but there is no way to call again.",
      "range": {
        "startLine": 720,
        "startChar": 8,
        "endLine": 720,
        "endChar": 45
      },
      "revId": "2510ba36a33a715e44e53f8c837b29a04adebc89",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}