{
  "comments": [
    {
      "key": {
        "uuid": "59ac6884_556ad830",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 9,
      "author": {
        "id": 1011221
      },
      "writtenOn": "2019-11-19T08:54:05Z",
      "side": 1,
      "message": "Please provide a sentence of two here about catching failure in background process in time.",
      "range": {
        "startLine": 7,
        "startChar": 0,
        "endLine": 9,
        "endChar": 0
      },
      "revId": "4764db57d5800e14070abc935fa313ab308b98b3",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    }
  ]
}