{
  "comments": [
    {
      "key": {
        "uuid": "124e6420_887deace",
        "filename": "lib/nvme/nvme_pcie.c",
        "patchSetId": 1
      },
      "lineNbr": 712,
      "author": {
        "id": 1012251
      },
      "writtenOn": "2018-11-28T08:30:42Z",
      "side": 1,
      "message": "Please output ERRLOG or WARNLOG.\n\nThis was other case but I observed an error due to secondary process but knowing the reason was not easy because descriptive error log was not collected.",
      "revId": "b4bff4cff5083375fff1973d8595d70801de4138",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}